config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :categories, param: :name do
    resources :puzzles, param: :name
  end

  root "categories#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :puzzles, dependent: :destroy, inverse_of: :category
  accepts_nested_attributes_for :puzzles, allow_destroy: true, reject_if: :all_blank

  mount_uploader :image_url, ImageUploader

  def to_param
    name.parameterize
  end

end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
  belongs_to :category, optional: true
  mount_uploader :image_url, ImageUploader

  def to_param
    name.parameterize
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order(:id)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by(name: params[:name].capitalize.tr("-", " "))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:id, :name, :image_url, puzzles_attributes: [:id, :name, :image_url, :_destroy])
    end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  before_action :set_puzzle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /puzzles
  # GET /puzzles.json
  def index
    @puzzles = Puzzle.all
  end

  # GET /puzzles/1
  # GET /puzzles/1.json
  def show
    @piecesNumber = 6
    @piecesNumberArray = (1..@piecesNumber).to_a.shuffle
    @piecesNumberWidth = 3
    @piecesNumberHeight = 2

    if params[:piecesnumber] !=  nil
      @piecesNumber = params[:piecesnumber].to_i
      @piecesNumberArray = (1..@piecesNumber).to_a.shuffle
      @piecesNumberWidth = params[:piecesnumberwidth].to_i
      @piecesNumberHeight = params[:piecesnumberheight].to_i
    end

    @category = Category.find(@puzzle.category_id)

    puzzle_array_ids = Puzzle.where(category_id: @puzzle.category_id).pluck(:id)
    puzzle_array_ids.delete(@puzzle.id)
    random_puzzle_ids = puzzle_array_ids.sample(4)
    @random_puzzles =  Puzzle.where(id: random_puzzle_ids)

    category_array_ids = Category.pluck(:id)
    category_array_ids.delete(@puzzle.category_id)
    random_category_ids = category_array_ids.sample(4)
    @random_categories = Category.where(id: random_category_ids)

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /puzzles/new
  def new
    @puzzle = Puzzle.new
  end

  # GET /puzzles/1/edit
  def edit
  end

  # POST /puzzles
  # POST /puzzles.json
  def create
    @puzzle = Puzzle.new(puzzle_params)

    respond_to do |format|
      if @puzzle.save
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully created.' }
        format.json { render :show, status: :created, location: @puzzle }
      else
        format.html { render :new }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puzzles/1
  # PATCH/PUT /puzzles/1.json
  def update
    respond_to do |format|
      if @puzzle.update(puzzle_params)
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully updated.' }
        format.json { render :show, status: :ok, location: @puzzle }
      else
        format.html { render :edit }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puzzles/1
  # DELETE /puzzles/1.json
  def destroy
    @puzzle.destroy
    respond_to do |format|
      format.html { redirect_to puzzles_url, notice: 'Puzzle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puzzle
      @puzzle = Puzzle.find_by(name:  params[:name].capitalize.tr("-", " "))
    end

    # Only allow a list of trusted parameters through.
    def puzzle_params
      params.require(:puzzle).permit(:name, :image_url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for category do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.file_field :image_url %>
    <%= image_tag @category.image_url.to_s, alt: @category.image_url.to_s, class: "img-responsive"%>
  </div>

  <div class="nested-puzzles" id="puzzles">
    <h2>Editing Puzzles</h2>
    <div class="row edit-puzzles-title">
      <div class="col-5">
        <p>Puzzle Name</p>
      </div>
      <div class="col-6">
        <p>Puzzle Image Url</p>
      </div>
      <div class="col-1">
        <p>Delete</p>
      </div>
    </div>
    <%= f.fields_for :puzzles do |puzzle| %>
      <%= render 'puzzle_fields', f: puzzle %>
    <% end %>
    <div class="links">
      <%= link_to_add_association "<i class='fas fa-plus'></i> Add Puzzle".html_safe, f, :puzzles, class: "btn" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_puzzle_fields.html.erb
<div class="nested-fields row">
  <div class="field col-5">
    <%= f.label :name, class: "sr-only" %>
    <%= f.text_field :name %>
  </div>

  <div class="field col-6">
    <%= f.label :image_url, class: "sr-only" %>
    <%= f.file_field :image_url %>
    <% if f.index != "new_puzzles" %> <!-- Do not show image if add new puzzle was clicked, else gets the img of the first puzzle of category -->
      <%= image_tag @category.puzzles[f.index.to_f].image_url_url(:edit_thumb).to_s, alt: @category.puzzles[f.index.to_f].image_url.to_s, class: "img-responsive" %>
    <% end %>
  </div>
  <%= link_to_remove_association "<i class='fas fa-trash-alt'></i>".html_safe, f, class: "col-1 text-center" %>
</div>

app/views/categories/edit.html.erb
<% content_for :title, "Edit " + @category.name + " - Animal Puzzles" %>
<div class="container-fluid category-edit">
  <h1>Editing Category</h1>

  <%= render 'form', category: @category %>

  <br>
  <%= link_to 'Delete Category', @category, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn form-btn delete'%>
  <br>
  <br>
  <%= link_to 'Show ' + @category.name, @category, class: 'btn form-btn' %>
  <%= link_to 'Back to Homepage', categories_path, class: 'btn form-btn' %>
</div>

app/views/categories/index.html.erb
<% content_for :title, "Animal Puzzles - Block Puzzles with Animals for Kids" %>
<div class="container text-center categories-index">

  <h1>Animal Puzzles</h1>

  <div class="row group-cards">
    <% @categories.each do |category| %>
      <div class="col-sm-6 card">
        <%= link_to category, :action => 'go' do %>
          <%= image_tag category.image_url_url(:index_thumb).to_s, alt: category.name, class: "img-responsive" %>
          <h2><%= category.name %></h2>
        <% end %>
      </div>
    <% end %>
  </div> <!-- end row -->

  <% if user_signed_in? %>
    <br>
    <%= link_to 'New Category', new_category_path, class: 'btn form-btn' %>
  <% end %>
</div>

app/views/categories/new.html.erb
<% content_for :title, "Create New Category - Animal Puzzles" %>
<div class="container-fluid">
  <h1>New Category</h1>

  <%= render 'form', category: @category %>

  <br>
  <%= link_to 'Back to Homepage', categories_path, class: 'btn form-btn' %>
</div>

app/views/categories/show.html.erb
<% content_for :title, @category.name + " - Animal Puzzles" %>
<div class="container text-center category-show">
  <h1>Animals of the <%= @category.name %></h1>

  <div class="row group-cards">
    <% @category.puzzles.each do |puzzle| %>
      <div class="col-sm-6 col-md-4 card">
        <%= link_to [@category, puzzle], :action => 'go' do %>
          <%= image_tag puzzle.image_url_url(:index_thumb).to_s, alt: puzzle.name, class: "img-responsive" %>
          <h2><%= puzzle.name %></h2>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= link_to  'Check out all Animals', root_path, class:"btn btn-viewer" %>

  <% if user_signed_in? %>
    <br>
    <br>
    <%= link_to 'Edit ' + @category.name, edit_category_path(@category), class: 'btn form-btn' %>
  <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title><%= yield(:title) %></title>

    <!-- Favicon Tag -->
    <%= favicon_link_tag asset_path('favicon.png') %>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&family=Architects+Daughter&family=Cabin+Sketch:wght@400;700&family=Caveat+Brush&family=Chewy&family=Comfortaa:wght@300;400;500;700&family=Coming+Soon&family=Fira+Sans:ital,wght@0,100;0,200;0,300;1,400;1,500&family=Gloria+Hallelujah&family=Handlee&family=Indie+Flower&family=McLaren&family=Poiret+One&family=Ranchers&family=Rancho&family=Shadows+Into+Light&family=Shadows+Into+Light+Two&family=Unkempt:wght@400;700&display=swap" rel="stylesheet">

    <!-- Google Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Font Awesome 5 Icons -->
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>

    <!-- Javascript -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
  </head>


  <body>
    <div class="anchor">
    <!-- flash messages -->
    <div class="container flash-messages">
      <% if notice %>
        <p id="notice" class="alert alert-info", role="alert"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p id="alert" class="alert alert-danger", role="alert"><%= alert %></p>
      <% end %>
    </div>

    <div class="text-center">
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn form-btn logout" %>
      <% end %>
    </div>

    <div class="main-body">
      <%= yield %>
    </div>
  </div>

    <hr>
    <footer>
      <div class="row">
        <p class="col-sm-6 order-sm-12 unsplash">All photos from <%= link_to 'Unsplash', 'https://unsplash.com/', target: :_blank %></p>
        <p class="col-sm-6 order-sm-1 copyright">&copy; <%= Date.today.year %> <%= link_to 'Elina Charalampous', 'https://elinacharalampous.gr', target: :_blank %></p>
      </div>
    </footer>
    <!-- main body ends here -->
  </body>
</html>

app/views/puzzles/_form.html.erb
<%= form_with(model: puzzle, local: true) do |form| %>
  <% if puzzle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(puzzle.errors.count, "error") %> prohibited this puzzle from being saved:</h2>

      <ul>
      <% puzzle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <br>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.file_field :image_url %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/puzzles/edit.html.erb
<div class="container-fluid puzzle-edit">
  <h1>Editing Puzzle</h1>

  <%= render 'form', puzzle: @puzzle %>

  <br>
  <br>
  <%= link_to 'Show ' + @puzzle.name, @puzzle, class: "btn form-btn" %>
</div>

app/views/puzzles/index.html.erb
<h1>Puzzles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puzzles.each do |puzzle| %>
      <tr>
        <td><%= puzzle.name %></td>
        <td><%= puzzle.image_url %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/puzzles/new.html.erb
<h1>New Puzzle</h1>

<%= render 'form', puzzle: @puzzle %>

<%= link_to 'Back', puzzles_path %>

app/views/puzzles/show.html.erb
<% content_for :title, @puzzle.name + " - Animal Puzzles" %>
<div class="container-fluid text-center puzzle-show">

  <div class="title">
    <h1><%= @puzzle.name %></h1>

  </div>

  <div class="row puzzle-pieces-side">
    <div class="col-2 pieces pieces-left">
      <% @piecesNumberArray[0..@piecesNumber/2-1].each do |i| %>
        <div class="piece<%= i %> piece draggable" id="draggable-piece<%= i %>"></div>
      <% end %>
    </div>
    <div class="col-8 main-puzzle" data-pieces-number="<%= @piecesNumber %>" data-pieces-number-width="<%= @piecesNumberWidth %>" data-pieces-number-height ="<%= @piecesNumberHeight %>" data-image-url = "<%= @puzzle.image_url.to_s %>" >
      <% (1..@piecesNumberHeight).each do |h| %>
        <div class="row">
          <% (1..@piecesNumberWidth).each do |w| %>
            <div class="piece<%= (h-1)*@piecesNumberWidth + w %> piece droppable" id="droppable-piece<%= (h-1)*@piecesNumberWidth + w %>"></div>
          <% end %>
        </div>
      <% end %>

    </div>
    <div class="col-2 pieces pieces-right">
      <% @piecesNumberArray[@piecesNumber/2..@piecesNumber+1].each do |i| %>
        <div class="piece<%= i %> piece draggable" id="draggable-piece<%= i %>"></div>
      <% end %>
    </div>
  </div> <!-- end row -->

  <div class="possibilities row">
    <div class="col-12 col-md-2 order-2 order-md-1 buttons d-md-block">
      <div class="button">
        <%= link_to '<i class="material-icons">arrow_back</i>'.html_safe, @category, class:"back-btn", title: 'Go back to ' + @category.name + ' Puzzles', data: { toggle: 'tooltip', placement: 'bottom'} %>
      </div>
      <div class="button">
        <%= link_to '<i class="material-icons">refresh</i>'.html_safe, category_puzzle_path(piecesnumber: @piecesNumber, piecesnumberwidth: @piecesNumberWidth, piecesnumberheight: @piecesNumberHeight), class:"back-btn", title: 'Refresh Puzzle', data: { toggle: 'tooltip', placement: 'bottom'} %>
      </div>
    </div> <!-- end butttons -->

    <div class="col-12 col-md-8 order-1 order-md-2 pieces-selection">
      <%= link_to category_puzzle_path(piecesnumber: 4, piecesnumberwidth: 2, piecesnumberheight: 2), remote: false do %>
        <div class="piece-selection" id="piece-selection-4">
          <%= image_tag("puzzle-2-green.png", class: "img-fluid", alt: "puzzle piece") %>
          <p>4</p>
        </div>
      <% end %>
      <%= link_to category_puzzle_path(piecesnumber: 6, piecesnumberwidth: 3, piecesnumberheight: 2), remote: false do %>
        <div class="piece-selection" id="piece-selection-6">
          <%= image_tag("puzzle-2-green.png", class: "img-fluid", alt: "puzzle piece") %>
          <p>6</p>
        </div>
      <% end %>
      <%= link_to category_puzzle_path(piecesnumber: 12, piecesnumberwidth: 4, piecesnumberheight: 3), remote: false do %>
        <div class="piece-selection" id="piece-selection-12">
          <%= image_tag("puzzle-2-green.png", class: "img-fluid", alt: "puzzle piece") %>
          <p>12</p>
        </div>
      <% end %>
      <%= link_to category_puzzle_path(piecesnumber: 16, piecesnumberwidth: 4, piecesnumberheight: 4), remote: false do %>
        <div class="piece-selection" id="piece-selection-16">
          <%= image_tag("puzzle-2-green.png", class: "img-fluid", alt: "puzzle piece") %>
          <p>16</p>
        </div>
      <% end %>
    </div><!-- end pieces-selection -->

  </div><!-- end possibilities -->

  <div class="additional-puzzles">
    <div class="same-category">
      <p>More <%= @category.name %> Animals</p>
      <div class="row group-cards">
        <% @random_puzzles.each do |random_puzzle| %>
          <div class="col-sm-6 col-md-3 card">
            <%= link_to [@category, random_puzzle], :action => 'go' do %>
              <%= image_tag random_puzzle.image_url_url(:index_thumb).to_s, alt: random_puzzle.name, class: "img-responsive" %>
              <h2><%= random_puzzle.name %></h2>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= link_to  'All ' +@category.name + ' Animals', @category, class:"btn btn-viewer" %>
    </div> <!-- end same-category -->

    <hr>
    <div class="all-categories">
      <p>More Animals</p>
      <div class="row group-cards">
        <% @random_categories.each do |random_category| %>
          <div class="col-sm-6 col-md-3 card">
            <%= link_to random_category, :action => 'go' do %>
              <%= image_tag random_category.image_url_url(:index_thumb).to_s, alt: random_category.name, class: "img-responsive" %>
              <h2><%= random_category.name %></h2>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= link_to  'All Animals', root_path, class:"btn btn-viewer" %>
    </div> <!-- end all-categories -->
  </div> <!-- end additional-puzzles -->

</div>

app/views/puzzles/show.js.erb
console.log("yes")

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, "Editing User " + @user.name + " - Animal Puzzles" %>
<div class="container user-login text-center">
  <h1>Editing User</h1>

  <%= render 'form', user: @user %>

  <br>
  <br>
  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<% content_for :title, "Users Overview - Animal Puzzles" %>
<div class="container user-login text-center">

  <h1>Users</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= link_to 'Show |', user %></td>
          <td><%= link_to 'Edit |', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<% content_for :title, "Create New User - Animal Puzzles" %>
<div class="container user-login text-center">
  <h1>New User</h1>

  <%= render 'form', user: @user %>

  <br>
  <br>
  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<% content_for :title, "User " + @user.name + " - Animal Puzzles" %>
<div class="container user-login text-center">

  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>